### ISSUE TITLE
Run Time Error 429

### ISSUE THREAD

**Issue by LornaSIL** [silnrsi/silconverters#4]
I did a Zoom call with someone who was having trouble with the converter.

First of all we had to uninstall SIL Converters 3.1, then SIL Converters 5.0, then SIL Converters 5.0.0. I think we did it in that order and she did have to reboot once or twice in there.

She is on Windows 8.1 and using Office 365 and it's 64bit.

We installed the newest SIL Converters 5.0 from October 13 (SIL Converters x64 installer (for 64-bit Office) 5.0).

Then we opened Word and went to the Addins and tried to add the converter from there and got the attached error message.

![RTE429](https://user-images.githubusercontent.com/7071907/144085294-91bbee49-93d5-4851-8cf0-42427ab2477c.jpg)

I don't know what that means or how to get around it.

I had her close Word and then we reopened it as "Administrator" and got the same error message.

But, in the end, we used the Bulk Word Converter and we could add the converter through that way. The Bulk Converter worked fine. Then we opened a doc in Word and another in Publisher and the converter that we had just added worked fine, so the problem was just in Add ins. Then, I asked her to go back to Add ins and try adding another converter and we got the same message.

Anyway, she's functional now since she doesn't think she'll need to add more converters, but I wondered if this was a bug anyone else encountered and if there is a known solution.

**Comment by bobeaton** [comment]
The Bulk Word Document Converter is preferred. The Word Document Template DOT add-in (which is the one I assume you tried) has some bugs in converting things in footnotes, etc., which aren't there in BWDC. 
This particular error, though, is fixable. It's due to the differences in Visual Basic for Word between the different versions of Word (and presumably, she had a version of Word that the latest DOT wasn't set for).

For the future, the solution is:
a) (probably need to move the Word Document Template DOT out of the folder it's installed in (e.g. something like, C:\Users\<user>\AppData\Roaming\Microsoft\Word\STARTUP (so it can be edited while not being 'loaded')
b) edit the *.dot file in Word
c) once it's opened, it has instructions on how to open the Visual Basic Editor and fix the references for the required COM assemblies. 
d) after making the changes, save the file and put it back in the 'STARTUP' folder
